name: moru_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  protobuf: ^3.1.0
  fixnum: ^1.1.1
  base32: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^17.0.0

ffigen:
  name: NativeLibrary
  description: 'Bindings for libmoru'
  output: 'lib/external/moru/generated_bindings.dart'
  headers:
    entry-points:
      - 'android/app/src/main/jniLibs/include/libmoru.h'
  preamble: |
    // ignore_for_file: always_specify_types
    // ignore_for_file: camel_case_types
    // ignore_for_file: non_constant_identifier_names
    // ignore_for_file: unused_field
    // ignore_for_file: unused_element
  comments:
    style: any
    length: full

flutter:
  uses-material-design: true
